//INIT MAP
export const INITIAL_MAP = "INITIAL_MAP";

//INFO ADDRESS
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_FAILURE = "GET_ADDRESS_FAILURE";

//POINT ADDRESS
export const SELECTED_INFO = "SELECTED_INFO";

//GET DATA MAIN CHART
export const GET_MAIN_CHART_REQUEST = "GET_MAIN_CHART_REQUEST";
export const GET_MAIN_CHART_SUCCESS = "GET_MAIN_CHART_SUCCESS";
export const GET_MAIN_CHART_FAILURE = "GET_MAIN_CHART_FAILURE";

//GET DATA TABLE HOME
export const GET_TABLE_HOME_REQUEST = "GET_TABLE_HOME_REQUEST";
export const GET_TABLE_HOME_SUCCESS = "GET_TABLE_HOME_SUCCESS";
export const GET_TABLE_HOME_FAILURE = "GET_TABLE_HOME_FAILURE";

//GET TOP
export const GET_TOP_REQUEST = "GET_TOP_REQUEST";
export const GET_TOP_SUCCESS = "GET_TOP_SUCCESS";
export const GET_TOP_FAILURE = "GET_TOP_FAILURE";


//SET SUGGESTIONS
export const SET_SUGGESTIONS = "SET_SUGGESTIONS";

//SET CHOSEN LOCATION
//export const SET_CHOSEN_LOCATION = "SET_CHOSEN_LOCATION";
